kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: wordpress-ruta
  namespace: pipeline-helm
  labels:
    app.kubernetes.io/instance: helm-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wordpress
    helm.sh/chart: wordpress-15.3.4
spec:
  host: >-
    wordpress-ruta-pipeline-helm.apps.cluster-7nz25.7nz25.sandbox1644.opentlc.com
  to:
    kind: Service
    name: helm-release-wordpress
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
